### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by piyush6348** [CodersForLife/Data-Structures-Algorithms#1]

**Comment by ankitkataria** [comment]
can i start working on the mentioned issue? if someone hasn't claimed it already?

**Comment by piyush6348** [comment]
yes please go ahead @ankitkataria just mention in which language you are going to code.

**Comment by ankitkataria** [comment]
i used cpp, submitted a pull request.

**Comment by cheungaustin** [comment]
Made a pull request with a Java implementation! 😸
