### ISSUE TITLE
Dijkstra

### ISSUE THREAD

**Issue by avisionx** [CodersForLife/Data-Structures-Algorithms#18]
Dijkstra for graph will be good too!

**Comment by piyush6348** [comment]
Go ahead @avisionx Just follow contribution guidelines

**Comment by hg398** [comment]
can i do this?

**Comment by piyush6348** [comment]
@avisionx, @hg398   in which language are you going to implement?

**Comment by hg398** [comment]
C++

**Comment by avisionx** [comment]
Python
