### ISSUE TITLE
Bit manipulation - check if a number is power of 2

### ISSUE THREAD

**Issue by ungps** [CodersForLife/Data-Structures-Algorithms#74]
Yes.

**Comment by ungps** [comment]
https://github.com/CodersForLife/Data-Structures-Algorithms/pull/71

**Comment by shivhek25** [comment]
I would like to add the code for the same in c++.

**Comment by mahak-bagha** [comment]
I would like to do it in JAVA

**Comment by hugomd** [comment]
I'll do this in JavaScript 👍
