### ISSUE TITLE
Repository file structure

### ISSUE THREAD

**Issue by FranciscoKnebel** [CodersForLife/Data-Structures-Algorithms#81]
Hey, just found your repository via Hacktoberfest issues. The idea is very interesting, but I found it confusing that implementations aren't separated into individual folders for each language.

A setup like this is more easily maintainable (and allows easier search)
`Category > Algorithm Name > Language > Implementation Name`

This allows for easier search of multiple implementations of the algorithm in the chosen language.

Example:
`Sorting > Bubble Sort > JavaScript > ImplementationName.js`

I could submit a PR with these changes, but it depends on first merging the pending PRs.

**Comment by nimit95** [comment]
We have that plan @FranciscoKnebel but we are waiting for repo codebase to grow larger. As we have put the restriction on the names so currently, we search easily. But for future definitely heads up

**Comment by FranciscoKnebel** [comment]
Alright. Changing now would be easier than handling and renaming hundreds of files later, but if you have other plans, no problem.
