### ISSUE TITLE
LICENSE.md and expanding CONTRIBUTING.md

### ISSUE THREAD

**Issue by FranciscoKnebel** [CodersForLife/Data-Structures-Algorithms#82]
Licensing is really important. Since everything is intended to be open, I suggest just using [MIT](https://opensource.org/licenses/MIT), but if you have other ideas for it, please add it.

CONTRIBUTING.md is a bit vague in some points. It's clearly not strict on coding style patterns, perhaps by intention, but for maintainability, PR names should be strictly defined.
I suggest more specific rules for pull requests, so you can easily identify the type of PR and category, algorithm and language of the implementation.

I can suggest a structure for PRs, if you approve of this change, and then implement it on the markdown files.

**Comment by FranciscoKnebel** [comment]
@nimit95 @piyush6348 What do you think? :smile:

**Comment by nimit95** [comment]
yeah happy to accept changes :)

**Comment by FranciscoKnebel** [comment]
OK, I thought about some points for each PR:

## Pull Requests
We need to identify category, algorithm and language.
 - I suggest all new PRs need to be titled with a model, like `category: algorithm (language)`.
Ex1: `Sorting: Bubble Sort (C)`
Ex2: `Searching: Binary Search (Java)`
This model could be extended to include implementation name.

- The PR template should contain checkboxes for the definitions from CONTRIBUTION.md, so the contributor vouches that his changes follow the guidelines, which saves time on code reviews.

- PRs should be single commit only. You should squash all commits into one and then submit your changes, so it's easier to handle the code history.

## License
- OK to insert the MIT license or you have other plans?

**Comment by nimit95** [comment]
Yeah, all these things seem fine, can you change in readme and contribution.md and make a pull request?
